### PR TITLE
Feature/initial wire frame

### PR DESCRIPTION
**Pull request by Amtresu**
In this project, I've begun to build a program to keep track of various user scores. 

- I've implemented git-flow
- created the project with Webpack
- added in the initial wireframe with some personal styling
- added in some preliminary javascript
image

### CODE REVIEW

**Review by muneebulrehman — CHANGES_REQUESTED** [review]
Hi @Amtresu , 

Good job so far! I see you put a lot of effort into this project. However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- No linter errors
- Good design
- Good commit history

## Required Changes ♻️

- [x] Consider removing the node_modules folder from your repository.

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Amtresu** [comment]
Hi @muneebulrehman they accidentally got added due to an error, but I removed before I submitted this PR, 

Thanks

**Comment by muneebulrehman** [comment]
> Hi @muneebulrehman they accidentally got added due to an error, but I removed before I submitted this PR,
> 
> Thanks

Hey @Amtresu , the same folder still exists in the default branch. You need to remove it from there.

**Comment by BenMukebo** [comment]
- [ ] When you add the node_module to the .gitignone file but if is still visible in the repository, the reason for this is that you created the node_module file and committed it before adding it to the .gitigone file. to undo this you can run this command `git rm --cached  node_module`. then you can add and commit. with that the file will not be available in the repository. Hope that help :

**Comment by Amtresu** [comment]
Hi @BenMukebo , thanks for your answer, I already ran these commands and settled the issue, there is no node_modules present in my repo

**Review by BenMukebo — APPROVED** [review]
<h1>Status: Approve  :champagne:  :+1: :confetti_ball: 

### **Hi @Amtresu**, 

### **Congratulations! 🎉 Project Approved ✅**

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 


### To Highlight :1st_place_medal: 
- Your Pull Request has a proper title and description. ✔️  
- No Linter errors :heavy_check_mark: 
- The node_modules folder is added to .gitignore , keep rocking :rocket: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

- [OPTIONAL] It will be nice to add explicit steps to clone and run your project locally, as this will be of help to non-technical users. Please add descriptive steps from cloning your app to seeing the results displayed on the browser.. This includes `git clone URL` , `cd project_name`,  `npm install`, `npm start`, etc 🙃 

- please refer to this [template](https://github.com/microverseinc/readme-template), you can copy and paste the content but remember to customize it to your project.
Cheers :clinking_glasses:  and Happy coding!!! :dancers:💻  

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please ping me @BenMukebo when you comment so I can receive the notification.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
